"""Scheduler-neutral, interruption-safe Stage 12-P3 campaign orchestration."""

from .adapters import (
    FixtureWorkerFailure,
    GenericJobArrayAdapter,
    GenericJobArrayPlan,
    JobArrayEntry,
    LocalFixtureAdapter,
    LocalRunObservation,
)
from .contracts import (
    SchedulerCancellation,
    SchedulerObservation,
    SchedulerSubmission,
    validate_operational_status,
)
from .dag import CompiledCampaign, DagValidationError, compile_campaign
from .policy import (
    FAILURE_CATEGORIES,
    ConcurrencyProfile,
    RetryPolicy,
    SheddingPolicy,
    TierRule,
    WorkerCapabilities,
)
from .records import (
    CAMPAIGN_VERSION,
    CONTRACT_VERSION,
    JOB_VERSION,
    CampaignManifest,
    ExpectedArtifact,
    HashBoundReference,
    LogicalJobSpec,
    OutputContract,
    PriorityClass,
    ResourceClass,
    Stage12P3ContractError,
    canonical_json_bytes,
    canonical_sha256,
    logical_job_from_mapping,
)
from .state import (
    ACTIVE_STATES,
    JOB_STATES,
    TERMINAL_STATES,
    CampaignController,
    CampaignStateError,
    DurableStateStore,
)

__all__ = [
    "CAMPAIGN_VERSION",
    "CONTRACT_VERSION",
    "JOB_VERSION",
    "CampaignManifest",
    "CampaignController",
    "CampaignStateError",
    "CompiledCampaign",
    "ConcurrencyProfile",
    "DagValidationError",
    "ExpectedArtifact",
    "FAILURE_CATEGORIES",
    "FixtureWorkerFailure",
    "GenericJobArrayAdapter",
    "GenericJobArrayPlan",
    "HashBoundReference",
    "LogicalJobSpec",
    "JobArrayEntry",
    "LocalFixtureAdapter",
    "LocalRunObservation",
    "OutputContract",
    "PriorityClass",
    "RetryPolicy",
    "ResourceClass",
    "SchedulerCancellation",
    "SchedulerObservation",
    "SchedulerSubmission",
    "SheddingPolicy",
    "Stage12P3ContractError",
    "TierRule",
    "WorkerCapabilities",
    "DurableStateStore",
    "JOB_STATES",
    "ACTIVE_STATES",
    "TERMINAL_STATES",
    "canonical_json_bytes",
    "canonical_sha256",
    "compile_campaign",
    "logical_job_from_mapping",
    "validate_operational_status",
]
