"""Policy-neutral Stage 12-P5 Fourier causal-interchange runner."""

from .capacity import CapacityAccounting, account_payload, validate_comparison_capacity
from .contracts import (
    CONDITIONS,
    AlignmentProfile,
    CapacityContract,
    FourierCoordinateContract,
    LocationContract,
    ModelReference,
    PairContract,
    Stage12P5ContractError,
    TrialContract,
    trial_from_mapping,
)
from .controls import (
    ControlUnavailableError,
    build_comparison_payloads,
    derive_condition_seed,
    deterministic_derangement,
)
from .fourier import (
    ActivationAdapter,
    AlignmentPlan,
    ArrayActivationAdapter,
    ExtractedCoordinateState,
    FourierTransformAdapter,
    InterventionPayload,
    NumpyFourierAdapter,
    extract_coordinates,
    fit_linear_alignment,
)
from .runner import (
    CensoredOutcome,
    ComparisonSetResult,
    ConditionExecutionRecord,
    FailureRecord,
    OutcomeObservation,
    RunInterrupted,
    UnavailableCondition,
    build_logical_job,
    record_unavailable_comparison_set,
    reduce_comparison_set,
    run_comparison_set,
    seal_result_with_p3,
)

__all__ = [
    "CONDITIONS",
    "ActivationAdapter",
    "AlignmentPlan",
    "AlignmentProfile",
    "ArrayActivationAdapter",
    "CapacityAccounting",
    "CapacityContract",
    "CensoredOutcome",
    "ComparisonSetResult",
    "ConditionExecutionRecord",
    "ControlUnavailableError",
    "ExtractedCoordinateState",
    "FailureRecord",
    "FourierCoordinateContract",
    "FourierTransformAdapter",
    "InterventionPayload",
    "LocationContract",
    "ModelReference",
    "NumpyFourierAdapter",
    "OutcomeObservation",
    "PairContract",
    "RunInterrupted",
    "Stage12P5ContractError",
    "TrialContract",
    "UnavailableCondition",
    "account_payload",
    "build_comparison_payloads",
    "build_logical_job",
    "record_unavailable_comparison_set",
    "derive_condition_seed",
    "deterministic_derangement",
    "extract_coordinates",
    "fit_linear_alignment",
    "reduce_comparison_set",
    "run_comparison_set",
    "seal_result_with_p3",
    "trial_from_mapping",
    "validate_comparison_capacity",
]
